/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.apis;

import com.kubevault.client.ApiException;
import io.kubernetes.client.models.V1APIGroupList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApisApi
 */
@Ignore
public class ApisApiTest {

    private final ApisApi api = new ApisApi();

    
    /**
     * 
     *
     * get available API versions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIVersionsTest() throws ApiException {
        V1APIGroupList response = api.getAPIVersions();

        // TODO: test validations
    }
    
}
