/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kubevault.client.models.ComGithubKubevaultOperatorApisCoreV1alpha1EtcdSpec;
import com.kubevault.client.models.ComGithubKubevaultOperatorApisCoreV1alpha1GcsSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BackendStorageSpec defines storage backend configuration of vault
 */
@ApiModel(description = "BackendStorageSpec defines storage backend configuration of vault")

public class ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec {
  @SerializedName("etcd")
  private ComGithubKubevaultOperatorApisCoreV1alpha1EtcdSpec etcd = null;

  @SerializedName("gcs")
  private ComGithubKubevaultOperatorApisCoreV1alpha1GcsSpec gcs = null;

  @SerializedName("inmem")
  private Boolean inmem = null;

  public ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec etcd(ComGithubKubevaultOperatorApisCoreV1alpha1EtcdSpec etcd) {
    this.etcd = etcd;
    return this;
  }

   /**
   * Get etcd
   * @return etcd
  **/
  @ApiModelProperty(value = "")
  public ComGithubKubevaultOperatorApisCoreV1alpha1EtcdSpec getEtcd() {
    return etcd;
  }

  public void setEtcd(ComGithubKubevaultOperatorApisCoreV1alpha1EtcdSpec etcd) {
    this.etcd = etcd;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec gcs(ComGithubKubevaultOperatorApisCoreV1alpha1GcsSpec gcs) {
    this.gcs = gcs;
    return this;
  }

   /**
   * Get gcs
   * @return gcs
  **/
  @ApiModelProperty(value = "")
  public ComGithubKubevaultOperatorApisCoreV1alpha1GcsSpec getGcs() {
    return gcs;
  }

  public void setGcs(ComGithubKubevaultOperatorApisCoreV1alpha1GcsSpec gcs) {
    this.gcs = gcs;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec inmem(Boolean inmem) {
    this.inmem = inmem;
    return this;
  }

   /**
   * ref: https://www.vaultproject.io/docs/configuration/storage/in-memory.html
   * @return inmem
  **/
  @ApiModelProperty(value = "ref: https://www.vaultproject.io/docs/configuration/storage/in-memory.html")
  public Boolean isInmem() {
    return inmem;
  }

  public void setInmem(Boolean inmem) {
    this.inmem = inmem;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec comGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec = (ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec) o;
    return Objects.equals(this.etcd, comGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec.etcd) &&
        Objects.equals(this.gcs, comGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec.gcs) &&
        Objects.equals(this.inmem, comGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec.inmem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(etcd, gcs, inmem);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubKubevaultOperatorApisCoreV1alpha1BackendStorageSpec {\n");
    
    sb.append("    etcd: ").append(toIndentedString(etcd)).append("\n");
    sb.append("    gcs: ").append(toIndentedString(gcs)).append("\n");
    sb.append("    inmem: ").append(toIndentedString(inmem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

