/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * KubernetesSecretSpec contain the fields that required to unseal using kubernetes secret
 */
@ApiModel(description = "KubernetesSecretSpec contain the fields that required to unseal using kubernetes secret")

public class ComGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec {
  @SerializedName("secretName")
  private String secretName = null;

  public ComGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec secretName(String secretName) {
    this.secretName = secretName;
    return this;
  }

   /**
   * Get secretName
   * @return secretName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSecretName() {
    return secretName;
  }

  public void setSecretName(String secretName) {
    this.secretName = secretName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec comGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec = (ComGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec) o;
    return Objects.equals(this.secretName, comGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec.secretName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secretName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubKubevaultOperatorApisCoreV1alpha1KubernetesSecretSpec {\n");
    
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

