/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus
 */

public class ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus {
  @SerializedName("active")
  private String active = null;

  @SerializedName("sealed")
  private List<String> sealed = null;

  @SerializedName("standby")
  private List<String> standby = null;

  @SerializedName("unsealed")
  private List<String> unsealed = null;

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus active(String active) {
    this.active = active;
    return this;
  }

   /**
   * PodName of the active Vault node. Active node is unsealed. Only active node can serve requests. Vault service only points to the active node.
   * @return active
  **/
  @ApiModelProperty(value = "PodName of the active Vault node. Active node is unsealed. Only active node can serve requests. Vault service only points to the active node.")
  public String getActive() {
    return active;
  }

  public void setActive(String active) {
    this.active = active;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus sealed(List<String> sealed) {
    this.sealed = sealed;
    return this;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus addSealedItem(String sealedItem) {
    if (this.sealed == null) {
      this.sealed = new ArrayList<String>();
    }
    this.sealed.add(sealedItem);
    return this;
  }

   /**
   * PodNames of Sealed Vault nodes. Sealed nodes MUST be unsealed to become standby or leader.
   * @return sealed
  **/
  @ApiModelProperty(value = "PodNames of Sealed Vault nodes. Sealed nodes MUST be unsealed to become standby or leader.")
  public List<String> getSealed() {
    return sealed;
  }

  public void setSealed(List<String> sealed) {
    this.sealed = sealed;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus standby(List<String> standby) {
    this.standby = standby;
    return this;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus addStandbyItem(String standbyItem) {
    if (this.standby == null) {
      this.standby = new ArrayList<String>();
    }
    this.standby.add(standbyItem);
    return this;
  }

   /**
   * PodNames of the standby Vault nodes. Standby nodes are unsealed. Standby nodes do not process requests, and instead redirect to the active Vault.
   * @return standby
  **/
  @ApiModelProperty(value = "PodNames of the standby Vault nodes. Standby nodes are unsealed. Standby nodes do not process requests, and instead redirect to the active Vault.")
  public List<String> getStandby() {
    return standby;
  }

  public void setStandby(List<String> standby) {
    this.standby = standby;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus unsealed(List<String> unsealed) {
    this.unsealed = unsealed;
    return this;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus addUnsealedItem(String unsealedItem) {
    if (this.unsealed == null) {
      this.unsealed = new ArrayList<String>();
    }
    this.unsealed.add(unsealedItem);
    return this;
  }

   /**
   * PodNames of Unsealed Vault nodes.
   * @return unsealed
  **/
  @ApiModelProperty(value = "PodNames of Unsealed Vault nodes.")
  public List<String> getUnsealed() {
    return unsealed;
  }

  public void setUnsealed(List<String> unsealed) {
    this.unsealed = unsealed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus comGithubKubevaultOperatorApisCoreV1alpha1VaultStatus = (ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus) o;
    return Objects.equals(this.active, comGithubKubevaultOperatorApisCoreV1alpha1VaultStatus.active) &&
        Objects.equals(this.sealed, comGithubKubevaultOperatorApisCoreV1alpha1VaultStatus.sealed) &&
        Objects.equals(this.standby, comGithubKubevaultOperatorApisCoreV1alpha1VaultStatus.standby) &&
        Objects.equals(this.unsealed, comGithubKubevaultOperatorApisCoreV1alpha1VaultStatus.unsealed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, sealed, standby, unsealed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubKubevaultOperatorApisCoreV1alpha1VaultStatus {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    sealed: ").append(toIndentedString(sealed)).append("\n");
    sb.append("    standby: ").append(toIndentedString(standby)).append("\n");
    sb.append("    unsealed: ").append(toIndentedString(unsealed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

