/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kubevault.client.models.ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret;
import io.kubernetes.client.models.V1ListMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList
 */

public class ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("items")
  private List<ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret> items = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private V1ListMeta metadata = null;

  public ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList items(List<ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret> items) {
    this.items = items;
    return this;
  }

  public ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList addItemsItem(ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret> getItems() {
    return items;
  }

  public void setItems(List<ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecret> items) {
    this.items = items;
  }

  public ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList metadata(V1ListMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public V1ListMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(V1ListMeta metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList comGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList = (ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList) o;
    return Objects.equals(this.apiVersion, comGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList.apiVersion) &&
        Objects.equals(this.items, comGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList.items) &&
        Objects.equals(this.kind, comGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList.kind) &&
        Objects.equals(this.metadata, comGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, items, kind, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubKubevaultOperatorApisExtensionsV1alpha1VaultSecretList {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

