/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kubevault.client.models.ComGithubKubevaultOperatorApisCoreV1alpha1StaticTLS;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TLSPolicy defines the TLS policy of the vault nodes
 */
@ApiModel(description = "TLSPolicy defines the TLS policy of the vault nodes")

public class ComGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy {
  @SerializedName("static")
  private ComGithubKubevaultOperatorApisCoreV1alpha1StaticTLS _static = null;

  public ComGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy _static(ComGithubKubevaultOperatorApisCoreV1alpha1StaticTLS _static) {
    this._static = _static;
    return this;
  }

   /**
   * StaticTLS enables user to use static x509 certificates and keys, by putting them into Kubernetes secrets, and specifying them here. If this is not set, operator will auto-gen TLS assets and secrets.
   * @return _static
  **/
  @ApiModelProperty(value = "StaticTLS enables user to use static x509 certificates and keys, by putting them into Kubernetes secrets, and specifying them here. If this is not set, operator will auto-gen TLS assets and secrets.")
  public ComGithubKubevaultOperatorApisCoreV1alpha1StaticTLS getStatic() {
    return _static;
  }

  public void setStatic(ComGithubKubevaultOperatorApisCoreV1alpha1StaticTLS _static) {
    this._static = _static;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy comGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy = (ComGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy) o;
    return Objects.equals(this._static, comGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy._static);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_static);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubKubevaultOperatorApisCoreV1alpha1TLSPolicy {\n");
    
    sb.append("    _static: ").append(toIndentedString(_static)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

