/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GoogleKmsGcsSpec contain the fields that required to unseal vault
 */
@ApiModel(description = "GoogleKmsGcsSpec contain the fields that required to unseal vault")

public class ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec {
  @SerializedName("bucket")
  private String bucket = null;

  @SerializedName("credentialPath")
  private String credentialPath = null;

  @SerializedName("kmsCryptoKey")
  private String kmsCryptoKey = null;

  @SerializedName("kmsKeyRing")
  private String kmsKeyRing = null;

  @SerializedName("kmsLocation")
  private String kmsLocation = null;

  @SerializedName("kmsProject")
  private String kmsProject = null;

  public ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec bucket(String bucket) {
    this.bucket = bucket;
    return this;
  }

   /**
   * The name of the Google Cloud Storage bucket to store values in
   * @return bucket
  **/
  @ApiModelProperty(required = true, value = "The name of the Google Cloud Storage bucket to store values in")
  public String getBucket() {
    return bucket;
  }

  public void setBucket(String bucket) {
    this.bucket = bucket;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec credentialPath(String credentialPath) {
    this.credentialPath = credentialPath;
    return this;
  }

   /**
   * Google application credential path
   * @return credentialPath
  **/
  @ApiModelProperty(value = "Google application credential path")
  public String getCredentialPath() {
    return credentialPath;
  }

  public void setCredentialPath(String credentialPath) {
    this.credentialPath = credentialPath;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec kmsCryptoKey(String kmsCryptoKey) {
    this.kmsCryptoKey = kmsCryptoKey;
    return this;
  }

   /**
   * The name of the Google Cloud KMS crypto key to use
   * @return kmsCryptoKey
  **/
  @ApiModelProperty(required = true, value = "The name of the Google Cloud KMS crypto key to use")
  public String getKmsCryptoKey() {
    return kmsCryptoKey;
  }

  public void setKmsCryptoKey(String kmsCryptoKey) {
    this.kmsCryptoKey = kmsCryptoKey;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec kmsKeyRing(String kmsKeyRing) {
    this.kmsKeyRing = kmsKeyRing;
    return this;
  }

   /**
   * The name of the Google Cloud KMS key ring to use
   * @return kmsKeyRing
  **/
  @ApiModelProperty(required = true, value = "The name of the Google Cloud KMS key ring to use")
  public String getKmsKeyRing() {
    return kmsKeyRing;
  }

  public void setKmsKeyRing(String kmsKeyRing) {
    this.kmsKeyRing = kmsKeyRing;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec kmsLocation(String kmsLocation) {
    this.kmsLocation = kmsLocation;
    return this;
  }

   /**
   * The Google Cloud KMS location to use (eg. &#39;global&#39;, &#39;europe-west1&#39;)
   * @return kmsLocation
  **/
  @ApiModelProperty(required = true, value = "The Google Cloud KMS location to use (eg. 'global', 'europe-west1')")
  public String getKmsLocation() {
    return kmsLocation;
  }

  public void setKmsLocation(String kmsLocation) {
    this.kmsLocation = kmsLocation;
  }

  public ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec kmsProject(String kmsProject) {
    this.kmsProject = kmsProject;
    return this;
  }

   /**
   * The Google Cloud KMS project to use
   * @return kmsProject
  **/
  @ApiModelProperty(required = true, value = "The Google Cloud KMS project to use")
  public String getKmsProject() {
    return kmsProject;
  }

  public void setKmsProject(String kmsProject) {
    this.kmsProject = kmsProject;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec = (ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec) o;
    return Objects.equals(this.bucket, comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec.bucket) &&
        Objects.equals(this.credentialPath, comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec.credentialPath) &&
        Objects.equals(this.kmsCryptoKey, comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec.kmsCryptoKey) &&
        Objects.equals(this.kmsKeyRing, comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec.kmsKeyRing) &&
        Objects.equals(this.kmsLocation, comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec.kmsLocation) &&
        Objects.equals(this.kmsProject, comGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec.kmsProject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucket, credentialPath, kmsCryptoKey, kmsKeyRing, kmsLocation, kmsProject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubKubevaultOperatorApisCoreV1alpha1GoogleKmsGcsSpec {\n");
    
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    credentialPath: ").append(toIndentedString(credentialPath)).append("\n");
    sb.append("    kmsCryptoKey: ").append(toIndentedString(kmsCryptoKey)).append("\n");
    sb.append("    kmsKeyRing: ").append(toIndentedString(kmsKeyRing)).append("\n");
    sb.append("    kmsLocation: ").append(toIndentedString(kmsLocation)).append("\n");
    sb.append("    kmsProject: ").append(toIndentedString(kmsProject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

