/*
 * KubeVault
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * Contact: kubevault@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubevault.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kubevault.client.models.V1alpha1GoogleKmsGcsSpec;
import com.kubevault.client.models.V1alpha1KubernetesSecretSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ModeSPpec contain unseal mechanism
 */
@ApiModel(description = "ModeSPpec contain unseal mechanism")

public class V1alpha1ModeSpec {
  @SerializedName("googleKmsGcs")
  private V1alpha1GoogleKmsGcsSpec googleKmsGcs = null;

  @SerializedName("kubernetesSecret")
  private V1alpha1KubernetesSecretSpec kubernetesSecret = null;

  public V1alpha1ModeSpec googleKmsGcs(V1alpha1GoogleKmsGcsSpec googleKmsGcs) {
    this.googleKmsGcs = googleKmsGcs;
    return this;
  }

   /**
   * Get googleKmsGcs
   * @return googleKmsGcs
  **/
  @ApiModelProperty(value = "")
  public V1alpha1GoogleKmsGcsSpec getGoogleKmsGcs() {
    return googleKmsGcs;
  }

  public void setGoogleKmsGcs(V1alpha1GoogleKmsGcsSpec googleKmsGcs) {
    this.googleKmsGcs = googleKmsGcs;
  }

  public V1alpha1ModeSpec kubernetesSecret(V1alpha1KubernetesSecretSpec kubernetesSecret) {
    this.kubernetesSecret = kubernetesSecret;
    return this;
  }

   /**
   * Get kubernetesSecret
   * @return kubernetesSecret
  **/
  @ApiModelProperty(value = "")
  public V1alpha1KubernetesSecretSpec getKubernetesSecret() {
    return kubernetesSecret;
  }

  public void setKubernetesSecret(V1alpha1KubernetesSecretSpec kubernetesSecret) {
    this.kubernetesSecret = kubernetesSecret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ModeSpec v1alpha1ModeSpec = (V1alpha1ModeSpec) o;
    return Objects.equals(this.googleKmsGcs, v1alpha1ModeSpec.googleKmsGcs) &&
        Objects.equals(this.kubernetesSecret, v1alpha1ModeSpec.kubernetesSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(googleKmsGcs, kubernetesSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ModeSpec {\n");
    
    sb.append("    googleKmsGcs: ").append(toIndentedString(googleKmsGcs)).append("\n");
    sb.append("    kubernetesSecret: ").append(toIndentedString(kubernetesSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

